# Generated by Django 3.2.4 on 2021-06-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210616_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='hours_played',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
