# Generated by Django 3.2.4 on 2021-06-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210616_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='game_list',
            field=models.ManyToManyField(to='profiles.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='game',
            name='steam_id',
        ),
        migrations.AddField(
            model_name='game',
            name='steam_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/static/css/img/avatar.png', upload_to='avatar/'),
        ),
    ]
