# Generated by Django 3.2.4 on 2021-06-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20210622_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='hours_played',
        ),
    ]
